### ISSUE TITLE
intel-power-control does not work on Mageia Linux

### ISSUE THREAD

**Issue by yullaw** [jmechnich/intel-power-control#1]
Hello,
intel-power-control does not start after installing required dependencies (gcc, Qt 5.x, python3) and compilation on Mageia 5b3.

HW: GPU: Intel + nVidia Optimus GeForce710M

```
# cat /etc/issue:
Mageia release 5 (Cauldron) for x86_64
Kernel 3.19.0-desktop-5.mga5 on a 4-processor x86_64 / \l
```

```
# lspcidrake |grep VGA:
Card:NVIDIA GeForce 420 series and later: NVIDIA Corporation|GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] [DISPLAY_VGA] (rev: a1)
Card:Intel 810 and later: Intel Corporation|3rd Gen Core processor Graphics Controller [DISPLAY_VGA] (rev: 09)
```

```
[root@localhost yullaw]# intel-power-control
Traceback (most recent call last):
  File "/usr/local/bin/intel-power-control", line 645, in <module>
    main()
  File "/usr/local/bin/intel-power-control", line 641, in main
    i = IntelPowerControl()
  File "/usr/local/bin/intel-power-control", line 44, in __init__
    self.updateAll()
  File "/usr/local/bin/intel-power-control", line 373, in updateAll
    self.updateValues()
  File "/usr/local/bin/intel-power-control", line 462, in updateValues
    os.path.join(self.gpubasepath,k,'gt_cur_freq_mhz')))),
ValueError: invalid literal for int() with base 10: ''
[root@localhost yullaw]# 
```

**Comment by jmechnich** [comment]
Hi yullaw,

thanks for your feedback. I think that the problem might be caused by the fact that you have multiple graphics cards in your system (which I hadn't tested so far). Could you run a 'git pull', 'sudo make install' and try again?

**Comment by yullaw** [comment]
Hi jmechnich,
perfect, now it works !!! :) No fault during start and I can see as the same as your screenshot.
Thanks!
Closing...
